### PR TITLE
Added support for the Tags API call.

### PR DESCRIPTION
**Pull request by ericthornton**
Added support for the Tags API call and did a slight refactoring of the
statistics. Tags/Info returns a stats property, so I changed
MandrillStats to be the aggregate stats instead of MandrillUserStats
which was just abstracting the aggregate stats. Also, moved the stats
and aggregate stats up a level in the structure.

### CODE REVIEW

**Comment by ericthornton** [comment]
I'm pretty sure the CI build failed because I didn't include my API key in the project. Tests run fine locally when I include the API key.

**Comment by feinoujc** [comment]
@ericthornton yes you are right, its because travis doesn't include the the secure environment vars in PR's http://docs.travis-ci.com/user/pull-requests/. Since you are my first PR I'm just finding this out! I'm working on it. Do you mind If I push to your remote to sort it out?

Thanks by the way!

**Comment by ericthornton** [comment]
Yeah I was hard coding the test tag. I should be able to add this for you.

**Comment by feinoujc** [comment]
Looks great! thanks for your contribution

**Comment by feinoujc** [comment]
@ericthornton I'll update nuget later today

**Pull request merged**
